<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo3lexikon"
 *
 * Auto generated by Extension Builder 2015-11-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Typo3lexikon',
    'description' => 'Template for my own page',
    'category' => 'plugin',
    'author' => 'Stefan Froemken',
    'author_email' => 'froemken@gmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.99.99',
            'fs_code_snippet' => '1.8.*'
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
