version: 1.0
deploy:
  # comment in one of the following lines to force the use of the recurring or bootstrap configuration
  #  force: bootstrap
  #  force: recurring

  # configure the initial deployment of each branch
  bootstrap:
    # directories that are not overwritten or removed by the next deployment
    excludes:
      - .ddev
      - public/fileadmin
      - public/uploads

    # Commands that are executed on the runtime after new files are copied
    post-deployment-remote-commands:
      # Activate AdditionalConfiguration.php
      - php -r "file_exists('./public/typo3conf/AdditionalConfiguration.php') || copy('./public/typo3conf/AdditionalConfiguration.example.php', './public/typo3conf/AdditionalConfiguration.php');"
      # Set execution bit for files in vendor/bin
      - chmod +x ./vendor/bin/*
      # Update DB schema
      - php ./vendor/bin/typo3cms database:updateschema "*.add,*.change"
      # Update language labels
      - php ./vendor/bin/typo3cms language:update
      # Clear Cache
      - php ./vendor/bin/typo3cms cache:flush

  # configure all following deployments of each branch
  recurring:
    # directories that are not overwritten or removed by the next deployment
    excludes:
      - .ddev
      - public/fileadmin
      - public/uploads

    # Commands that are executed on the runtime after new files are copied
    post-deployment-remote-commands:
      # Set execution bit for files in vendor/bin
      - chmod +x ./vendor/bin/*
      # Update DB schema
      - php ./vendor/bin/typo3cms database:updateschema "*.add,*.change"
      # Update language labels
      - php ./vendor/bin/typo3cms language:update
      # Clear Cache
      - php ./vendor/bin/typo3cms cache:flush
