#!/bin/bash

## Description: Executes deployer (Command: dep) to deploy your project to foreign servers
## Usage: dep [options] [arguments]
## Example: "ddev dep list" or "ddev dep --version"

/var/www/html/vendor/bin/dep $@
